// <auto-generated />
using System;
using Employee_Management_System_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Management_System_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250629045233_Adding_Role_Claims")]
    partial class Adding_Role_Claims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AttendancePub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendanceUID");

                    b.HasIndex("EmployeeUID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentPub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentUID");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.HasIndex("DepartmentPub_ID")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeePub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RoleUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeUID");

                    b.HasIndex("DepartmentUID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleUID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("LeaveUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeavePub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveUID");

                    b.HasIndex("EmployeeUID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Payroll", b =>
                {
                    b.Property<Guid>("PayrollUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Allowances")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BasicSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Deductions")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.Property<string>("PayrollPub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PayrollUID");

                    b.HasIndex("EmployeeUID");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.PerformanceReview", b =>
                {
                    b.Property<Guid>("ReviewUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewPub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ReviewUID");

                    b.HasIndex("EmployeeUID");

                    b.ToTable("PerformanceReviews", t =>
                        {
                            t.HasCheckConstraint("CK_PerformanceReview_Score", "[Score] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.PhoneNumber", b =>
                {
                    b.Property<Guid>("PhoneNumberUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("PhoneNumberPub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumberValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhoneNumberUID");

                    b.HasIndex("EmployeeUID");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectPub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectUID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.ProjectAssignment", b =>
                {
                    b.Property<Guid>("AssignmentUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<string>("AssignmentPub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("EmployeeUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ProjectUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("RoleInProject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssignmentUID");

                    b.HasIndex("EmployeeUID");

                    b.HasIndex("ProjectUID");

                    b.ToTable("EmployeeProjectAssignments");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RolePub_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("RoleUID");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6"),
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("376e5a0e-dd14-4394-8ab9-0d02889972c5"),
                            Name = "HRManager",
                            NormalizedName = "HRMANAGER"
                        },
                        new
                        {
                            Id = new Guid("ed02f158-8363-434f-9b2e-254c77c45c64"),
                            Name = "HRStaff",
                            NormalizedName = "HRSTAFF"
                        },
                        new
                        {
                            Id = new Guid("701747f8-ce70-4bf8-8b7c-e09c28d27cfe"),
                            Name = "HRAssistant",
                            NormalizedName = "HRASSISTANT"
                        },
                        new
                        {
                            Id = new Guid("18db8396-7473-4f53-9b1e-1155e65047ff"),
                            Name = "PayrollOfficer",
                            NormalizedName = "PAYROLLOFFICER"
                        },
                        new
                        {
                            Id = new Guid("189f9797-aeec-481f-9154-4fc630590017"),
                            Name = "PayrollAssistant",
                            NormalizedName = "PAYROLLASSISTANT"
                        },
                        new
                        {
                            Id = new Guid("b7f60b18-dc58-4d0d-9d3e-d4b3c8ee9a3a"),
                            Name = "LeaveApprover",
                            NormalizedName = "LEAVEAPPROVER"
                        },
                        new
                        {
                            Id = new Guid("34a71f5e-b93d-410b-a9b5-695bbad9c407"),
                            Name = "LeaveCoordinator",
                            NormalizedName = "LEAVECOORDINATOR"
                        },
                        new
                        {
                            Id = new Guid("337ca893-79ce-4d45-a1af-8d335f76cec7"),
                            Name = "ProjectManager",
                            NormalizedName = "PROJECTMANAGER"
                        },
                        new
                        {
                            Id = new Guid("543737ed-030e-47b2-9808-881ee43d2568"),
                            Name = "ProjectLead",
                            NormalizedName = "PROJECTLEAD"
                        },
                        new
                        {
                            Id = new Guid("a9e1d827-52d6-40d9-9f00-616e19212417"),
                            Name = "ProjectCoordinator",
                            NormalizedName = "PROJECTCOORDINATOR"
                        },
                        new
                        {
                            Id = new Guid("6ceb9ca1-4f8d-43e0-8d57-0f8d0205801c"),
                            Name = "TeamLead",
                            NormalizedName = "TEAMLEAD"
                        },
                        new
                        {
                            Id = new Guid("6eb74c93-108c-4481-9662-cfa244899f46"),
                            Name = "DepartmentHead",
                            NormalizedName = "DEPARTMENTHEAD"
                        },
                        new
                        {
                            Id = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94"),
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = new Guid("415a4bd3-44c1-4725-b66f-362ed30a7b9d"),
                            Name = "Intern",
                            NormalizedName = "INTERN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Attendance.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Attendance.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Attendance.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Attendance.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Attendance.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Department.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Department.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Department.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Department.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Department.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Employee.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Employee.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Employee.Attendance",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Employee.LeaveRequest",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Employee.Payroll",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "Employee.PerformanceReview",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Employee.PhoneNumbers",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Employee.ProjectAssignment",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "Employee.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Employee.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Employee.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "LeaveRequest.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "LeaveRequest.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "LeaveRequest.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "LeaveRequest.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "LeaveRequest.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Payroll.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Payroll.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "Payroll.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "Payroll.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "Payroll.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "PerformanceReview.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "PerformanceReview.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "PerformanceReview.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "PerformanceReview.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "PerformanceReview.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "PhoneNumber.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "PhoneNumber.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "PhoneNumber.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "PhoneNumber.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "PhoneNumber.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "ProjectAssignment.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "ProjectAssignment.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "ProjectAssignment.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "ProjectAssignment.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "ProjectAssignment.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "Project.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "Project.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "Project.GetEmployees",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "Project.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "Project.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "Project.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "Role.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "Role.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "Role.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "Role.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "Role.Delete",
                            ClaimValue = "true",
                            RoleId = new Guid("6e70c831-1f14-44e8-ac9e-f02825bd65d6")
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "Employee.View",
                            ClaimValue = "true",
                            RoleId = new Guid("376e5a0e-dd14-4394-8ab9-0d02889972c5")
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "Department.View",
                            ClaimValue = "true",
                            RoleId = new Guid("376e5a0e-dd14-4394-8ab9-0d02889972c5")
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "LeaveRequest.Approve",
                            ClaimValue = "true",
                            RoleId = new Guid("376e5a0e-dd14-4394-8ab9-0d02889972c5")
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "LeaveRequest.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("376e5a0e-dd14-4394-8ab9-0d02889972c5")
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "Employee.View",
                            ClaimValue = "true",
                            RoleId = new Guid("ed02f158-8363-434f-9b2e-254c77c45c64")
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "LeaveRequest.View",
                            ClaimValue = "true",
                            RoleId = new Guid("ed02f158-8363-434f-9b2e-254c77c45c64")
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "Employee.View",
                            ClaimValue = "true",
                            RoleId = new Guid("701747f8-ce70-4bf8-8b7c-e09c28d27cfe")
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "Payroll.View",
                            ClaimValue = "true",
                            RoleId = new Guid("18db8396-7473-4f53-9b1e-1155e65047ff")
                        },
                        new
                        {
                            Id = 66,
                            ClaimType = "Payroll.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("18db8396-7473-4f53-9b1e-1155e65047ff")
                        },
                        new
                        {
                            Id = 67,
                            ClaimType = "Payroll.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("18db8396-7473-4f53-9b1e-1155e65047ff")
                        },
                        new
                        {
                            Id = 68,
                            ClaimType = "Payroll.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("18db8396-7473-4f53-9b1e-1155e65047ff")
                        },
                        new
                        {
                            Id = 69,
                            ClaimType = "Payroll.View",
                            ClaimValue = "true",
                            RoleId = new Guid("189f9797-aeec-481f-9154-4fc630590017")
                        },
                        new
                        {
                            Id = 70,
                            ClaimType = "Payroll.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("189f9797-aeec-481f-9154-4fc630590017")
                        },
                        new
                        {
                            Id = 71,
                            ClaimType = "LeaveRequest.View",
                            ClaimValue = "true",
                            RoleId = new Guid("b7f60b18-dc58-4d0d-9d3e-d4b3c8ee9a3a")
                        },
                        new
                        {
                            Id = 72,
                            ClaimType = "LeaveRequest.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("b7f60b18-dc58-4d0d-9d3e-d4b3c8ee9a3a")
                        },
                        new
                        {
                            Id = 73,
                            ClaimType = "LeaveRequest.View",
                            ClaimValue = "true",
                            RoleId = new Guid("34a71f5e-b93d-410b-a9b5-695bbad9c407")
                        },
                        new
                        {
                            Id = 74,
                            ClaimType = "Project.View",
                            ClaimValue = "true",
                            RoleId = new Guid("337ca893-79ce-4d45-a1af-8d335f76cec7")
                        },
                        new
                        {
                            Id = 75,
                            ClaimType = "Project.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("337ca893-79ce-4d45-a1af-8d335f76cec7")
                        },
                        new
                        {
                            Id = 76,
                            ClaimType = "Project.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("337ca893-79ce-4d45-a1af-8d335f76cec7")
                        },
                        new
                        {
                            Id = 77,
                            ClaimType = "ProjectAssignment.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("337ca893-79ce-4d45-a1af-8d335f76cec7")
                        },
                        new
                        {
                            Id = 78,
                            ClaimType = "ProjectAssignment.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("337ca893-79ce-4d45-a1af-8d335f76cec7")
                        },
                        new
                        {
                            Id = 79,
                            ClaimType = "ProjectAssignment.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("543737ed-030e-47b2-9808-881ee43d2568")
                        },
                        new
                        {
                            Id = 80,
                            ClaimType = "ProjectAssignment.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("543737ed-030e-47b2-9808-881ee43d2568")
                        },
                        new
                        {
                            Id = 81,
                            ClaimType = "Project.View",
                            ClaimValue = "true",
                            RoleId = new Guid("543737ed-030e-47b2-9808-881ee43d2568")
                        },
                        new
                        {
                            Id = 82,
                            ClaimType = "Project.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("543737ed-030e-47b2-9808-881ee43d2568")
                        },
                        new
                        {
                            Id = 83,
                            ClaimType = "Project.View",
                            ClaimValue = "true",
                            RoleId = new Guid("a9e1d827-52d6-40d9-9f00-616e19212417")
                        },
                        new
                        {
                            Id = 84,
                            ClaimType = "Project.ById",
                            ClaimValue = "true",
                            RoleId = new Guid("6ceb9ca1-4f8d-43e0-8d57-0f8d0205801c")
                        },
                        new
                        {
                            Id = 85,
                            ClaimType = "ProjectAssignment.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6ceb9ca1-4f8d-43e0-8d57-0f8d0205801c")
                        },
                        new
                        {
                            Id = 86,
                            ClaimType = "PerformanceReview.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6ceb9ca1-4f8d-43e0-8d57-0f8d0205801c")
                        },
                        new
                        {
                            Id = 87,
                            ClaimType = "PerformanceReview.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("6ceb9ca1-4f8d-43e0-8d57-0f8d0205801c")
                        },
                        new
                        {
                            Id = 88,
                            ClaimType = "PerformanceReview.Update",
                            ClaimValue = "true",
                            RoleId = new Guid("6ceb9ca1-4f8d-43e0-8d57-0f8d0205801c")
                        },
                        new
                        {
                            Id = 89,
                            ClaimType = "Department.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6eb74c93-108c-4481-9662-cfa244899f46")
                        },
                        new
                        {
                            Id = 90,
                            ClaimType = "PerformanceReview.View",
                            ClaimValue = "true",
                            RoleId = new Guid("6eb74c93-108c-4481-9662-cfa244899f46")
                        },
                        new
                        {
                            Id = 91,
                            ClaimType = "Employee.View",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 92,
                            ClaimType = "Employee.Attendance",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 93,
                            ClaimType = "Employee.LeaveRequest",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 94,
                            ClaimType = "Employee.Payroll",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 95,
                            ClaimType = "Employee.PerformanceReview",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 96,
                            ClaimType = "Employee.PhoneNumbers",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 97,
                            ClaimType = "Employee.ProjectAssignment",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 98,
                            ClaimType = "LeaveRequest.Create",
                            ClaimValue = "true",
                            RoleId = new Guid("349ad8bb-5d46-43f4-b21c-aafc6db97a94")
                        },
                        new
                        {
                            Id = 99,
                            ClaimType = "Employee.View",
                            ClaimValue = "true",
                            RoleId = new Guid("415a4bd3-44c1-4725-b66f-362ed30a7b9d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Employee_Management_System_API.Domain.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Payroll", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.PerformanceReview", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Employee", "Employee")
                        .WithMany("PerformanceReviews")
                        .HasForeignKey("EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.PhoneNumber", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Employee", "Employee")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.ProjectAssignment", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.Employee", "Employee")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_Management_System_API.Domain.Entities.Project", "Project")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("ProjectUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_Management_System_API.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Employee_Management_System_API.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Payrolls");

                    b.Navigation("PerformanceReviews");

                    b.Navigation("PhoneNumbers");

                    b.Navigation("ProjectAssignments");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Project", b =>
                {
                    b.Navigation("EmployeeAssignments");
                });

            modelBuilder.Entity("Employee_Management_System_API.Domain.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
